name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag riyazmenttech/todo-client:latest
        docker tag riyazmenttech/todo-client:latest riyazmenttech/todo-client:$(date +%s)
        docker build . --file Dockerfile --tag riyazmenttech/todo-server:latest
        docker tag riyazmenttech/todo-server:latest riyazmenttech/todo-server:$(date +%s)

    - name: Push the Docker images
      run: |
        docker push riyazmenttech/todo-client:latest
        docker push riyazmenttech/todo-client:$(date +%s)
        docker push riyazmenttech/todo-server:latest
        docker push riyazmenttech/todo-server:$(date +%s)
